apiVersion: v1
kind: Service
metadata:
  name: {{ include "sd-comfyui.fullname" . }}
  labels:
    {{- include "sd-comfyui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.comfyui.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "sd-comfyui.selectorLabels" . | nindent 4 }}
